"use client";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,CirclePlus,ClipboardCheck,Gauge,Loader2,Search,ShieldCheck,Wrench,Trash2,X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Tool={id:string;code:string;name:string;category:string|null;serial_number:string|null;location:string|null;responsible:string|null;condition:"serviceable"|"maintenance"|"out_of_service";calibration_required:boolean;last_calibration_date:string|null;next_calibration_date:string|null;certificate_reference:string|null};
type NCR={id:string;reference:string;title:string;owner:string|null;due_date:string|null;status:string;severity:string};
const empty={code:"",name:"",category:"",serial_number:"",location:"",responsible:"",condition:"serviceable",calibration_required:false,last_calibration_date:"",next_calibration_date:"",certificate_reference:""};
export function QualityWorkspace(){const sb=useMemo(()=>createClient(),[]);const [tools,setTools]=useState<Tool[]>([]);const[ncrs,setNcrs]=useState<NCR[]>([]);const[projectId,setProjectId]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[open,setOpen]=useState(false);const[form,setForm]=useState<any>(empty);const[saving,setSaving]=useState(false);
 async function load(){setLoading(true);setError("");const p=await sb.from("projects").select("id").eq("code","PDD").single();if(p.error){setError(p.error.message);setLoading(false);return;}setProjectId(p.data.id);const[t,n]=await Promise.all([sb.from("quality_tools").select("*").eq("project_id",p.data.id).order("code"),sb.from("quality_ncr").select("id,reference,title,owner,due_date,status,severity").eq("project_id",p.data.id).order("created_at",{ascending:false})]);if(t.error)setError("Exécutez d'abord supabase/sprint_013_foundation_quality.sql — "+t.error.message);else setTools(t.data||[]);if(!n.error)setNcrs(n.data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 const today=new Date().toISOString().slice(0,10),soon=new Date(Date.now()+30*864e5).toISOString().slice(0,10);const calibrated=tools.filter(t=>t.calibration_required);const expired=calibrated.filter(t=>t.next_calibration_date&&t.next_calibration_date<today);const expiring=calibrated.filter(t=>t.next_calibration_date&&t.next_calibration_date>=today&&t.next_calibration_date<=soon);const visible=tools.filter(t=>`${t.code} ${t.name} ${t.serial_number||""} ${t.responsible||""}`.toLowerCase().includes(query.toLowerCase()));
 async function save(e:React.FormEvent){e.preventDefault();if(!projectId)return;setSaving(true);const payload={...form,project_id:projectId,category:form.category||null,serial_number:form.serial_number||null,location:form.location||null,responsible:form.responsible||null,last_calibration_date:form.last_calibration_date||null,next_calibration_date:form.next_calibration_date||null,certificate_reference:form.certificate_reference||null};const r=await sb.from("quality_tools").insert(payload);if(r.error)setError(r.error.message);else{setOpen(false);setForm(empty);await load()}setSaving(false)}
 async function del(id:string){if(!confirm("Supprimer cet outillage ?"))return;const r=await sb.from("quality_tools").delete().eq("id",id);if(r.error)setError(r.error.message);else await load()}
 return <div className="mx-auto max-w-[1700px]"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><h1 className="text-4xl font-black">Quality Management</h1><p className="mt-2 font-bold text-[var(--opc-blue)]">4M, outillage, étalonnage, check-lists et non-conformités</p><p className="mt-2 text-sm text-[var(--opc-muted)]">La qualité devient une condition de clôture de chaque activité.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-[var(--opc-red)] px-5 py-3 text-sm font-black text-white"><CirclePlus className="h-4 w-4"/>Ajouter un outillage</button></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><K icon={Wrench} label="Outillages" value={tools.length}/><K icon={Gauge} label="À étalonner" value={calibrated.length}/><K icon={AlertTriangle} label="Étalonnage expiré" value={expired.length} danger/><K icon={AlertTriangle} label="Expire sous 30 j" value={expiring.length}/><K icon={ShieldCheck} label="NCR ouvertes" value={ncrs.filter(n=>n.status!=="closed").length} danger/></div>
 <section className="mt-6 grid gap-4 xl:grid-cols-4">{[["Man","Qualifications, habilitations, formations et équipes"],["Machine","Engins, moyens, outillage et disponibilité"],["Method","Procédures, modes opératoires, ITP et points d'arrêt"],["Material","Références, certificats, lots et conformité"]].map(([a,b],i)=><article key={a} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--opc-blue-soft)] font-black text-[var(--opc-blue)]">{i+1}M</span><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700">À configurer</span></div><h2 className="mt-4 text-lg font-black">{a}</h2><p className="mt-2 text-sm text-slate-500">{b}</p></article>)}</section>
 <section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">Registre des outillages & étalonnages</h2><p className="text-xs text-slate-500">Contrôle automatique des dates de validité</p></div><div className="flex items-center gap-2 rounded-xl border bg-slate-50 px-3 py-2"><Search className="h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher..." className="bg-transparent text-sm outline-none"/></div></div>{error&&<div className="m-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{loading?<div className="grid h-56 place-items-center"><Loader2 className="animate-spin"/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Code</th><th>Outillage</th><th>N° série</th><th>Localisation</th><th>Responsable</th><th>État</th><th>Prochain étalonnage</th><th>Certificat</th><th></th></tr></thead><tbody>{visible.map(t=>{const isExpired=t.next_calibration_date&&t.next_calibration_date<today;return <tr key={t.id} className="border-t"><td className="p-4 font-black text-[var(--opc-blue)]">{t.code}</td><td className="font-bold">{t.name}<div className="text-xs font-normal text-slate-400">{t.category||"—"}</div></td><td>{t.serial_number||"—"}</td><td>{t.location||"—"}</td><td>{t.responsible||"—"}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{t.condition}</span></td><td>{t.calibration_required?<span className={`font-black ${isExpired?"text-red-600":"text-emerald-700"}`}>{t.next_calibration_date||"Non renseigné"}</span>:"Non requis"}</td><td>{t.certificate_reference||"—"}</td><td><button onClick={()=>void del(t.id)} className="p-2 text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></td></tr>})}</tbody></table></div>}</section>
 <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><ClipboardCheck className="text-[var(--opc-blue)]"/><div><h2 className="font-black">Règle de clôture qualité</h2><p className="text-sm text-slate-500">Une activité restera « En attente de clôture » si les 4M, la check-list, les certificats ou les VT obligatoires ne sont pas conformes.</p></div></div></section>
 {open&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40"><div className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">Nouvel outillage</h2><p className="text-sm text-slate-500">Créer l'équipement et son cycle d'étalonnage.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2"><F label="Code"><input required className="input" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></F><F label="Nom"><input required className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></F><F label="Catégorie"><input className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></F><F label="N° série"><input className="input" value={form.serial_number} onChange={e=>setForm({...form,serial_number:e.target.value})}/></F><F label="Localisation"><input className="input" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></F><F label="Responsable"><input className="input" value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></F><F label="État"><select className="input" value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}><option value="serviceable">Conforme</option><option value="maintenance">Maintenance</option><option value="out_of_service">Hors service</option></select></F><label className="flex items-center gap-3 pt-8 font-bold"><input type="checkbox" checked={form.calibration_required} onChange={e=>setForm({...form,calibration_required:e.target.checked})}/>Étalonnage requis</label><F label="Dernier étalonnage"><input type="date" className="input" value={form.last_calibration_date} onChange={e=>setForm({...form,last_calibration_date:e.target.value})}/></F><F label="Prochain étalonnage"><input type="date" className="input" value={form.next_calibration_date} onChange={e=>setForm({...form,next_calibration_date:e.target.value})}/></F><F label="Référence certificat"><input className="input" value={form.certificate_reference} onChange={e=>setForm({...form,certificate_reference:e.target.value})}/></F><div className="sm:col-span-2 flex justify-end gap-3 pt-4"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3 font-bold">Annuler</button><button disabled={saving} className="rounded-xl bg-[var(--opc-blue)] px-5 py-3 font-black text-white">{saving?"Enregistrement...":"Créer"}</button></div></form></div></div>}<style jsx>{`.input{width:100%;border:1px solid var(--opc-border);border-radius:.75rem;padding:.75rem;outline:none}.input:focus{border-color:var(--opc-blue);box-shadow:0 0 0 4px rgba(0,80,164,.08)}`}</style></div>}
function K({icon:Icon,label,value,danger=false}:{icon:any;label:string;value:number;danger?:boolean}){return <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><Icon className={`h-5 w-5 ${danger?"text-red-500":"text-[var(--opc-blue)]"}`}/><span className="text-3xl font-black">{value}</span></div><p className="mt-3 text-sm font-bold text-slate-500">{label}</p></article>}
function F({label,children}:{label:string;children:React.ReactNode}){return <label><span className="text-sm font-black">{label}</span><div className="mt-2">{children}</div></label>}
